### ISSUE TITLE
Request: offer a tutorial of how to create the projects as on the samples

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google-ai-edge/litert-samples#28]
I'm actually interested in something very similar to the "super resolution" sample, but for any size of input&output.
I want to do the same as "super resolution" but with more flexibility. I've seen that there should be models for this.
It's weird that there are so many talks about AI, but I can't find a decent video/article that goes step-by-step of how to use it for Android.
I tried to ask even on reddit about this, and sadly nobody showed me of how to do it, despite all my efforts of searching about it:

https://www.reddit.com/r/tensorflow/comments/1dm2ovn/tensorflow_lite_on_android_possible_to_use_a/

Why here on this repository aren't there any links to how the samples were created?
Can you please make a video and a tutorial of how you've created the projects?

**Comment by PaulTR** [comment]
For larger sizes you'd need to train a new model. The model is what defines the input and output tensor shapes (essentially the input and output image sizes), so that's the limiting factor there. We're using one called ESRGAN, so you can find a tutorial on making that model here: https://www.tensorflow.org/hub/tutorials/image_enhancing

As for videos, it's on the TODO list, but I'm going to focus on codelabs and these samples first as the LiteRT rollout continues across platforms.

**Comment by AndroidDeveloperLB** [comment]
@PaulTR Wait, are you saying there are tutorials?
I'm very new to TensorFlow/LiteRT. 
I developed only for native Android apps for many years.
Where can I find about this?
Can you please show how to do it all, from the very beginning of creating a new Android app? 

As for the model, I know there are other models. That's why I wrote the sentence "I've seen that there should be models for this".
